version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiberguardian
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: fiberguardian-backend
    depends_on:
      - mariadb
    environment:
      # Config banco
      DB_URL: jdbc:mysql://mariadb:3306/fiberguardian?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: root

      # Config Flyway
      FLYWAY_URL: jdbc:mysql://mariadb:3306/fiberguardian?createDatabaseIfNotExist=true&serverTimezone=UTC
      FLYWAY_USER: root
      FLYWAY_PASSWORD: root

      # Storage
      STORAGE_DIR: /app/storage/pdf

      # Keystore (classpath, já dentro do jar)
      KEYSTORE_PATH: classpath:localhost.p12
      KEYSTORE_PASSWORD: ranger19
      KEYSTORE_TYPE: PKCS12
      KEYSTORE_ALIAS: localhost
      KEY_PASSWORD: ranger19

    ports:
      - "8443:8443"
    volumes:
      - backend_storage:/app/storage/pdf

volumes:
  db_data:
  backend_storage:
