version: '3.8'
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_fiberguardian
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiberguardian
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: