CREATE TABLE laboratorio (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_nota_fiscal_id BIGINT NOT NULL,
    numero_lote VARCHAR(45) NOT NULL,
    cvm DECIMAL(15,2) NOT NULL CHECK (cvm >= 0),
    pontos_finos INTEGER NOT NULL,
    pontos_grossos INTEGER NOT NULL,
    neps INTEGER NOT NULL CHECK (neps >= 0),
    h_pilosidade DECIMAL(15,2) NOT NULL CHECK (h_pilosidade > 0),
    resistencia DECIMAL(15,2) NOT NULL CHECK (resistencia >0),
    alongamento DECIMAL(15,2) NOT NULL CHECK (alongamento > 0),
    titulo_ne DECIMAL(15,2) NOT NULL CHECK (titulo_ne >= 0),
    torcao_t_m INTEGER NOT NULL CHECK (torcao_t_m >= 0),
    status ENUM('APROVADO', 'REPROVADO') NOT NULL,
    liberado_por BIGINT NOT NULL,
    observacao_laudo VARCHAR(255),
    data_realizacao DATE NOT NULL,
    data_cadastro DATETIME NOT NULL,
    data_alteracao DATETIME NULL,
    criado_por BIGINT NULL,
    alterado_por BIGINT NULL,
    CONSTRAINT uk_laboratorio_numero_lote UNIQUE (item_nota_fiscal_id,numero_lote),
    CONSTRAINT fk_laboratorio_item_nota_fiscal_id FOREIGN KEY (item_nota_fiscal_id) REFERENCES nota_item(id),
    CONSTRAINT fk_laboratorio_usuario_liberado FOREIGN KEY (liberado_por) REFERENCES usuario(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;